# Generated by Django 6.0.1 on 2026-01-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='latitede',
            new_name='latitude',
        ),
    ]
