# Generated by Django 6.0.1 on 2026-01-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_latitede_venue_latitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='weather',
        ),
        migrations.AddField(
            model_name='venue',
            name='weather',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
