# Generated by Django 6.0.1 on 2026-01-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_weather_venue_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.eventimage'),
        ),
    ]
